"use client";
import React, { useState } from "react";
import { ShieldCheck, Lock, ArrowRight } from "lucide-react";

export function MfaFlow() {
  const [code, setCode] = useState(["", "", "", "", "", ""]);
  const [verified, setVerified] = useState(false);

  const handleChange = (value: string, index: number) => {
    if (value.length <= 1) {
      const newCode = [...code];
      newCode[index] = value;
      setCode(newCode);
    }
  };

  return (
    <div className="max-w-md mx-auto p-8 bg-slate-900 border border-slate-800 rounded-2xl shadow-xl text-center">
      <div className="mx-auto w-12 h-12 bg-blue-600/10 text-blue-400 rounded-xl flex items-center justify-center mb-4 border border-blue-500/20">
        <Lock className="h-6 w-6" />
      </div>
      <h2 className="text-xl font-bold text-white mb-2">Two-Factor Authentication</h2>
      <p className="text-sm text-slate-400 mb-6">Enter the 6-digit security code generated by your authenticator app.</p>
      
      <div className="flex justify-center gap-2 mb-6">
        {code.map((digit, idx) => (
          <input
            key={idx}
            type="text"
            maxLength={1}
            value={digit}
            onChange={(e) => handleChange(e.target.value, idx)}
            className="w-12 h-12 text-center bg-slate-950 border border-slate-800 rounded-lg text-lg font-bold text-white focus:outline-none focus:border-blue-500"
          />
        ))}
      </div>

      <button
        onClick={() => setVerified(true)}
        className="w-full bg-blue-600 hover:bg-blue-500 text-white font-medium py-2.5 rounded-lg transition-colors flex items-center justify-center gap-2"
      >
        <span>Verify Code</span>
        <ArrowRight className="h-4 w-4" />
      </button>

      {verified && (
        <div className="mt-4 flex items-center justify-center gap-2 text-emerald-400 text-sm">
          <ShieldCheck className="h-4 w-4" />
          <span>Authentication Successful!</span>
        </div>
      )}
    </div>
  );
}
